config/routes.rb
Homerun::Application.routes.draw do
  resources :courses, :except => [:index, :show]
  resources :categories, :except => [:index, :show]
  resources :tasks do
    member do
      patch 'complete'
    end
  end

  root 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
  validates_presence_of :name
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :tasks
  validates_presence_of :name
end

app/models/task.rb
class Task < ActiveRecord::Base

  ULTIMATE_DUE_DATE = Chronic.parse "June 21, 2014"

  belongs_to :course
  belongs_to :category

  validates_presence_of :course, :category, :name, :points

  scope :completed, -> { where(complete: true) }
  scope :remaining, -> { where(complete: false) }
  scope :completed_today, -> { where(completed_on: Time.now.beginning_of_day..Time.now.end_of_day) }
  scope :by_completed_at, -> { order(completed_on: :desc) }
  scope :by_updated_at, -> { order(updated_at: :desc) }
  #scope :by_point_value, -> { order(points: :desc) }
  #scope :by_point_value_asc, -> { order(:points) }

  def self.search(params)
    response = Task.all
    if params[:id]
      return Task.where(:id => params[:id])
    end
    if params[:course]
      response = response.joins(:course).where(:courses => { :name => params[:course] })
    end
    if params[:category]
      response = response.joins(:category).where(:categories => { :name => params[:category] })
    end
    if params[:points]
      response = response.where(:points => params[:points])
    end
    if params[:sort]
      direction, sorter = params[:sort][0] == "-" ? [:desc, params[:sort][1..-1]] : [:asc, params[:sort]]
      case sorter
      when "course"
        response = response.joins(:course).order("courses.name #{direction}")
      when "category"
        response = response.joins(:category).order("categories.name #{direction}")
      when "name", "points"
        response = response.order(sorter => direction)
      end
    end
    response
  end

  def self.points_total
    all.inject(0) { |sum, task| sum + task.points }
  end

  def self.last_completed
    Task.completed.by_completed_at.first
  end

  def self.any_completed?
    all.where(complete: true).count > 0
  end

  def self.all_completed?
    all.where(complete: true).count == all.count
  end

  def self.days_until_due_date
    ((Time.now - ULTIMATE_DUE_DATE) / 60 / 60 / 24).abs.floor
  end

  def self.points_today
    completed_today.points_total
  end

  def self.points_per_day
    (remaining.points_total.to_f / days_until_due_date)
  end

  def self.good_day?
    points_today >= points_per_day
  end

  def complete=(val)
    if [true, "1"].include? val
      self.completed_on = Time.now
    else
      self.completed_on = nil
    end
    super(val)
  end

  def complete!
    self.update(complete: true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["USERNAME"] && password == ENV["PASSWORD"]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to root_path, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path, notice: 'Category was successfully deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy]

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to root_path, notice: 'Course was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @course.update(course_params)
      redirect_to root_path, notice: 'Course was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @course.destroy
    redirect_to root_path, notice: 'Course was successfully deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :complete]

  # GET /tasks
  # GET /tasks.json
  def index
    # TODO why do we have this last sorting method appended?
    # don't we mean to override that with params?
    # how is it working?
    @remaining_tasks = Task.search(params).remaining.by_updated_at
    @completed_tasks = Task.search(params).completed.by_completed_at
    @percent_complete = @completed_tasks.points_total.to_f / (@completed_tasks.points_total + @remaining_tasks.points_total).to_f * 100
    @total_percent_complete = Task.completed.points_total.to_f / Task.all.points_total.to_f * 100
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path, notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if @task.update(task_params)
      redirect_to root_path, notice: 'Task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def complete
    @task.complete!
    redirect_to :back, notice: 'Great job!'
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    redirect_to :back, notice: 'Task was successfully deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :points, :course_id, :category_id, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inspirational_message
    [
      "You're a star!",
      "You kick ass!",
      "You blow away the competition!",
      "Keep it going!",
      "You're on a roll!",
      "Hey, Einstein!",
      "Way to go!",
      "NYU, here you come!",
      "ты звезда",
      "Университет это весело"
    ].sample
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

app/views/layouts/_favicon.erb
<link href="data:image/x-icon;base64,AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA7+/vAP///wBCQv8AtbW1AM7OzgAAAMYA3t7eAOfn5wD39/cAwP/AAAAA/wC9vb0AxsbGANbW1gAAAAAAqqqgAAAKqqqqoA3WbEAKqqoFVVu13ECqoF7nfuZdxAqg53d3e+XcCgd3gRh3bl1AB4cXERh7ZcADsXmREYfrYAOxmZmRh+tgCBOyKZF3ddAIGSspkXd10KAZIrmRd+UKoBGZMRd35QqqAREbuH5QqqqgCIM3cAqqqqqgAAAKqqr4HwAA4AcAAMADAACAAQAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABAACAAQAAwAMAAOAHAAD4HwAA" rel="icon" type="image/x-icon" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homerun</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/favicon" %>
</head>
<body>

  <div class="container">

    <div class="page-header">
      <h1>
        <%= link_to "Homerun", root_path %>
        <small>
          <%= inspirational_message %>
        </small>
      </h1>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/tasks/_creation_buttons.html.erb
<div class="well">
  <%= link_to 'New Task', new_task_path, :class => "btn btn-primary" %>
  <%= link_to 'New Course', new_course_path, :class => "btn btn-primary"%>
  <%= link_to 'New Category', new_category_path, :class => "btn btn-primary"%>
</div>

app/views/tasks/_filters.html.erb
<div class="well">
  <h3>Filters and Sorts</h3>
  <% if params[:points] or params[:category] or params[:course] %>
    <p>Only showing tasks that meet these conditions:</p>
    <ul>
      <% if params[:points] %>
        <li>
          Worth <strong><%= pluralize params[:points], "point" %></strong>
          <span class="clear-param glyphicon glyphicon-remove-circle" data-clear="points"></span>
        </li>
      <% end %>
      <% if params[:category] %>
        <li>
          Categorized as <strong><%= params[:category].indefinitize %></strong>
          <span class="clear-param glyphicon glyphicon-remove-circle" data-clear="category"></span>
        </li>
      <% end %>
      <% if params[:course] %>
        <li>
          For <strong><%= params[:course] %></strong>
          <span class="clear-param glyphicon glyphicon-remove-circle" data-clear="course"></span>
        </li>
      <% end %>
    </ul>
    <p>Filtered complete: <%= @percent_complete.round(2) %>%</p>
    <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @percent_complete %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent_complete %>%"></div>
    </div>
  <% else %>
    <p><strong>If you want to filter</strong>, click on point values, category names, or course names to filter your tasks down to the ones you're interested in right now.</p>
  <% end %>
  <% if params[:sort] %>
    <p>
      Tasks are sorted by <strong><%= params[:sort] %></strong>
      <span class="clear-param glyphicon glyphicon-remove-circle" data-clear="sort"></span>
    </p>
  <% else %>
    <p>Tasks are sorted by most recently updated by default.</p>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.select :course_id, Course.all.order(:name).map { |c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.order(:name).map { |c| [c.name, c.id]} %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_statistics.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title">Statistics</h1>
  </div>
  <div class="panel-body">
    <p>
      You've completed
      <strong><%= pluralize Task.completed.points_total, "point" %> total</strong>.
      You have
      <strong><%= pluralize Task.remaining.points_total, "point" %> remaining</strong>.
    </p>
    <p>
      <% if Task.any_completed? %>
        It's been
        <strong><%= time_ago_in_words Task.last_completed.completed_on %></strong>
        since you've completed a task.
      <% else %>
        You haven't completed any tasks. Get to work!
      <% end %>
    </p>
    <p>
      You should earn at least
      <strong><%= Task.points_per_day %> points per day</strong>.
      So far today you've earned
      <strong><%= Task.points_today %> points</strong>.
      Keep it up!
    </p>
    <p>Total complete: <%= @total_percent_complete.round(2) %>%</p>
    <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @total_percent_complete %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @total_percent_complete %>%">
      </div>
    </div>
  </div>
</div>

app/views/tasks/_table.html.erb
<% if tasks.empty? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="panel-title">None!</h1>
    </div>
    <div class="panel-body">
      <p>There are no tasks to be found here!</p>
    </div>
  </div>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th title="Click to sort by name">Name</th>
        <th title="Click to sort by points">Points</th>
        <th title="Click to sort by course">Course</th>
        <th title="Click to sort by category">Category</th>
      </tr>
    </thead>

    <tbody>
      <% tasks.each do |task| %>
        <tr>
          <td class="name">
            <%= task.name %>
          </td>
          <td class="points" title="Click to filter/unfilter by tasks with <%= pluralize task.points, "point" %>"><%= task.points %></td>
          <td class="course" title="Click to filter/unfilter by <%= task.course.name %> tasks"><%= task.course.name %></td>
          <td class="category" title="Click to filter/unfilter by <%= task.category.name %> tasks" ><%= task.category.name %></td>
          <td>
            <% if task.complete? %>
              completed <%= time_ago_in_words task.completed_on %> ago
            <% else %>
              <%= link_to(complete_task_path(task), method: :patch, data: { confirm: 'Are you sure? Great job!' }, class: "btn btn-success", title: "Mark this task complete") do %>
                <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% end %>
            <%= link_to edit_task_path(task), class: "btn btn-warning", title: "Edit this task's details" do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", title: "Delete this task if necessary" do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="well">
  <%= link_to 'New Task', new_task_path, :class => "btn btn-primary" %>
  <%= link_to 'New Course', new_course_path, :class => "btn btn-primary"%>
  <%= link_to 'New Category', new_category_path, :class => "btn btn-primary"%>
</div>

<%= render "statistics" %>

<h2>Listing tasks</h2>

<%= render "filters" %>

<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li class="active"><a href="#remaining" data-toggle="tab">Remaining</a></li>
  <li><a href="#completed" data-toggle="tab">Completed</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="remaining">
    <%= render partial: "table", locals: { tasks: @remaining_tasks } %>
  </div>
  <div class="tab-pane" id="completed">
    <%= render partial: "table", locals: { tasks: @completed_tasks } %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>